# Generated by Django 5.2 on 2025-04-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nivel',
            field=models.CharField(blank=True, choices=[('primero', '1° Medio'), ('segundo', '2° Medio'), ('tercero', '3° Medio'), ('cuarto', '4° Medio')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('AutoridadDocente', 'AutoridadDocente')], default='Estudiante', max_length=50),
        ),
    ]
