# Generated by Django 5.2 on 2025-05-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoridadDocente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensayo',
            name='nivel',
            field=models.CharField(choices=[('primero', '1° Medio'), ('segundo', '2° Medio'), ('tercero', '3° Medio'), ('cuarto', '4° Medio')], max_length=50),
        ),
    ]
