# Generated by Django 5.2 on 2025-06-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoridadDocente', '0003_carga_preguntas_iniciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensayo',
            name='preguntas',
            field=models.ManyToManyField(blank=True, to='AutoridadDocente.pregunta'),
        ),
        migrations.AlterField(
            model_name='ensayo',
            name='temas',
            field=models.ManyToManyField(blank=True, to='AutoridadDocente.tema'),
        ),
    ]
