# Generated by Django 5.2 on 2025-06-13 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoridadDocente', '0004_alter_ensayo_preguntas_alter_ensayo_temas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('puntaje', models.FloatField(blank=True, null=True)),
                ('ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoridadDocente.ensayo')),
                ('estudiante', models.ForeignKey(limit_choices_to={'role': 'Estudiante'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa_elegida', models.CharField(max_length=1)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoridadDocente.pregunta')),
                ('respuesta_ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='AutoridadDocente.respuestaensayo')),
            ],
        ),
    ]
